baseurl = "/"
languageCode = "en-us"
title = "Spencer Woody"
theme = "spencer-hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Papers"
    url = "/papers/"
    weight = 2
[[menu.main]]
    name = "Talks"
    url = "/talks/"
    weight = 3
[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 4
# [[menu.main]]
#     name = "CV"
#     url = "https://spencerwoody.github.io/files/Woody-CV.pdf"
#     weight = 4
[[menu.main]]
    name = "Contact"
    url = "/#Contact"

[params]
    description = "Spencer Woody - PhD Student, Statistics"
    footer = "&copy; [Spencer Woody](https://spencerwoody.github.io) 2018 | [Github](https://github.com/spencerwoody)"
